---
title: "Text Analysis"
---

```{r}
#if (!require("devtools")) install.packages("devtools")
#install.packages("devtools")

#devtools::install_github("josiahparry/geniusR")
```

```{r}
if (!require("geniusR")) install.packages("geniusR")
library(geniusR)
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)


```

```{r}
swift = genius_album(artist = "Taylor Swift", album = "Reputation")
riri = genius_album(artist = "Rihanna", album = "Anti")
```

```{r}
library(tidytext)
tidy_swift = swift %>%
  unnest_tokens(word, lyric) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

tidy_riri = riri %>%
  unnest_tokens(word, lyric) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

```


```{r}
tidy_swift = tidy_swift %>%
  rename(swift_n = n) %>%
  mutate(swift_prop = swift_n/sum(swift_n))

tidy_riri = tidy_riri %>%
  rename(riri_n = n) %>%
  mutate(riri_prop = riri_n/sum(riri_n))
```

```{r}
compare_words = tidy_swift %>%
  full_join(tidy_riri, by = "word")

summary(compare_words)
```

```{r}
ggplot(compare_words, aes(swift_prop, riri_prop)) +
  geom_abline() +
  geom_text(aes(label=word), check_overlap = TRUE, vjust=1.5) +
  labs(y="Rihanna", x="Taylor Swift") + theme_classic()
```

#Over Time

```{r}
if (!require("rvest")) install.packages("rvest")
library(rvest)
riridisc = 'https://en.wikipedia.org/wiki/Rihanna_discography'

disc <- riridisc %>%
  read_html() %>%
  html_nodes(xpath = '//*[@id="mw-content-text"]/div/table[2]') %>%
  html_table(fill = TRUE)


ririAlbums = disc[[1]]
```


```{r}
TS_albums <- ririAlbums[2:9,1:2] %>%
  separate(`Album details`, c("Released","Month","Day","Year"),
           extra='drop') %>%
  select(c("Title","Year"))

TS_albums$Year<-as.numeric(TS_albums$Year)
```

```{r}
riri_lyrics = TS_albums %>%
  mutate(tracks = map2("Rihanna", Title, genius_album))
```

```{r}
riri_lyrics = riri_lyrics %>%
  unnest(tracks)
```

```{r}
library(tidytext)
tidy_riri <- riri_lyrics %>%
  unnest_tokens(word, lyric) %>%
  anti_join(stop_words)
```

```{r}
tidy_riri %>%
  count(word, sort=TRUE)
```

```{r}
words_by_year <- tidy_riri %>%
  count(Year, word) %>%
  group_by(Year) %>%
  mutate(time_total = sum(n)) %>%
  group_by(word) %>%
  mutate(word_total = sum(n)) %>%
  ungroup() %>%
  rename(count = n) %>%
  filter(word_total > 50)

nested_words <- words_by_year %>%
  nest(-word)

word_models <- nested_words %>%
  mutate(models = map(data, ~glm(cbind(count, time_total) ~ Year, .,
                                 family = "binomial")))
```


```{r}
library(broom)

slopes <- word_models %>%
  unnest(map(models, tidy)) %>%
  filter(term == "Year") %>%
  mutate(adjusted.p.value = p.adjust(p.value))

top_slopes <- slopes%>%
  filter(adjusted.p.value < 0.1) %>%
  select(-statistic, -p.value)
```

```{r}
library(scales)
words_by_year %>%
  inner_join(top_slopes, by = "word") %>%
  ggplot(aes(Year, count/time_total, color = word, lty = word)) +
  geom_line(size = 1.3) +
  labs(x = NULL, y = "Word Frequency") +
  scale_x_continuous(breaks=TS_albums$Year,
                     labels=TS_albums$Title) +
  scale_y_continuous(labels=scales::percent)
```














